services:
  web:
    build:
      context: .
    ports:
      - 8080:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
  db:
    image: 'postgres:16-alpine'
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5434:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
secrets:
  db-password:
    file: db/password.txt