# Generated by Django 5.1.2 on 2024-10-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='Transaction',
        ),
    ]
